Resources:
  SecretsExample:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secreto de prueba
      Name: /prueba/secreto1
      SecretString: '{"user": "user_test", "password":"super-secret-password"}'
      Tags:
        - Key: AppName
          Value: AppB