Resources:
  SecretsExample:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Testing secret
      Name: ${self:custom.secrets.name}
      SecretString: '{"user": "user_test", "password":"super-secret-password"}'  # Need to encrypt this