Resources:
  LambdaTriggerIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: ReadSecretTest
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Join [':', ["arn:aws:logs", 'eu-central-1', "775255162681", "log-group:/aws/lambda/*:*:*"]]  #To be changed to proper variables
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref SecretsExample
              - Effect: Allow
                Action:
                  - batch:*
                Resource: arn:aws:batch:*
